banner border colours
GSS-Cogs/idpd-frontend-homepage pull request #22
Opened 2023-08-25 13:12 UTC by StRhys

a `className` prop can now be passed to the header to change the bottom border colours.

**root header** used for homepage (css `root-header`)
![image](https://github.com/GSS-Cogs/idpd-frontend-homepage/assets/110108574/00e668ad-5611-4539-a047-ca302688a61e)

**non-root header** used for most other pages (css `non-root-header`)
![image](https://github.com/GSS-Cogs/idpd-frontend-homepage/assets/110108574/44481a19-ed32-4ef6-8446-c90f00bdb41e)

**non-root alternative header** used for topics page (css `non-root-alt-header`)
![image](https://github.com/GSS-Cogs/idpd-frontend-homepage/assets/110108574/74712cc3-71a9-440d-8b78-357fa4d6f75d)

2023-08-25 13:29 UTC, nimshi89 submitted a review, later dismissed
Looks Good To ME

2023-08-30 07:46 UTC, rossbowen commented
Small point but would go with [BEM](https://css-tricks.com/bem-101/) naming of the CSS classes, and to make them as descriptive as possible, maybe:

- `govuk-header--root-border`
- `govuk-header--non-root-border`
- `govuk-header--non-root-alt-border`

Or:
- `govuk-header--yellow-border`
- `govuk-header--blue-border`
- `govuk-header--blue-alt-border`

2023-09-01 11:42 UTC, rossbowen requested changes

2023-09-01 11:42 UTC, rossbowen commented on components/Header/index.tsx
> +
I think this approach is fine, but I wouldn't use a prop called `className` to achieve it - reason being, if I wanted to add an _additional_ class to the header for whatever reason, this means I have to do some classname injection to do it, e.g.

```jsx
<Header className="yellow-border ross-custom-class" />
```

Other thing you could so is enumerate the options in the type definition, e.g.

```jsx
borderType? : "yellow" | "blue" | "blue-alt"

2023-09-01 11:42 UTC, rossbowen commented on components/PhaseBanner/_phaseBanner.scss
> +.govuk-phase-banner.alternative {
Missed one for BEM naming.

2023-09-01 14:03 UTC, rossbowen approved these changes

2023-09-01 14:37 UTC, merged