App setup
GSS-Cogs/idpd-frontend-homepage pull request #9
Opened 2023-07-17 09:27 UTC by StRhys

This ticket compromises of 3 parts for the general setup of the data explorer
Make a simple Makefile to include some variables, should need expanding in future to include more options.

- enable graceful shutdown
Only on 'start' not 'dev' script

- /health endpoint
Following ons [specs](https://github.com/ONSdigital/dp-standards/blob/main/HEALTH_CHECK_SPECIFICATION.md)
```
make build
make start 
``` 
or `make debug`
Will get the full json for the health check

- JSON logging
Using [next-logging](https://github.com/sainsburys-tech/next-logger) library

2023-07-19 07:47 UTC, rossbowen requested changes

2023-07-19 07:47 UTC, rossbowen commented on src/app/health/route.ts
> +  const statusCode = await getStatusCode(NextResponse.next());
I can't get this line to return anything other than `200`, even when I try to make the application crash or make the homepage return `4XX` codes.

I think `NextResponse.next()` is for use in middleware, not inside routes.

I'm not sure what a typical thing would be here - maybe trying to fetch the homepage and seeing if that returns a `4XX` or `5XX` code?

2023-07-19 07:47 UTC, rossbowen commented on src/app/health/route.ts
> +  } else if (statusCode >= 400 && statusCode !== 429) {
This would cause any `40X` code, except `429` to return a health-check with code `500`.

So if the check returns a `403` or `404`, the health-check returns a `500`. Just wanted to double check that's the intention!

2023-07-19 14:19 UTC, rossbowen commented on src/app/health/route.ts
> +  } else if (statusCode >= 400 && statusCode !== 429) {
Yeah it seems like the intention!

> Any status code `>=400 && != 429` will be treated as a failure.

2023-07-25 12:38 UTC, StRhys commented on src/app/health/route.ts
> +  const statusCode = await getStatusCode(NextResponse.next());
I've replaced the `NextResponse.next()` with the suggested fetching of the homepage.
Getting the homepage url should work on local and when deployed without needing to change anything.

2023-07-25 13:54 UTC, rossbowen submitted a review, later dismissed

2023-07-28 14:58 UTC, rossbowen commented
I think something's happened during the merge, so I reset back to [254ba7a](https://github.com/GSS-Cogs/idpd-frontend-homepage/pull/9/commits/254ba7a3c0c3544c4bb5ef2f074eb3edbf055d04) by doing:

```sh
git reset --hard 254ba7a
```

...and from there tried to merge in main. 

```sh
git merge main
```

Then git threw me into a merge with conflicts, so I kept checking `git status` for files with conflicts, got those files into a state I was happy with and one by one added them with `git add`.

Main thing need was to move `/src/app/health` into just `/app/health`.

I've `--force`d the changes but this PR hasn't recognised them... so if need be I'll open a new PR.

2023-07-28 15:00 UTC, closed without merging